### ISSUE TITLE
Record a Screencast not working

### ISSUE THREAD

**Issue by whemix** [anthropics/claude-quickstarts#100]
![Untitled](https://github.com/user-attachments/assets/bbaab42a-0cde-4374-81e0-4216704cd325)

Is there a specific browser version number required?

 I am using Edge Browser version below on Macbook Pro 
 
 
![image](https://github.com/user-attachments/assets/9edca0f2-2b0e-4237-b677-ac3ee2abd56a)

**Comment by x5a** [comment]
@whemix feel free to file an issue with streamlit https://github.com/streamlit/streamlit/issues
