### ISSUE TITLE
Account for rate limiting issues.

### ISSUE THREAD

**Issue by valdo404** [anthropics/claude-quickstarts#102]
When running the demo, we are facing blocks due to to Claude rate limiting issues.

We should be able to wait for the rate limit completion.

Best,
Laurent

<img width="531" alt="Capture d’écran 2024-10-24 à 11 31 27 AM" src="https://github.com/user-attachments/assets/0f5fc00d-0e2c-48ed-9928-485ee21c004a">

**Comment by hippoduck** [comment]
Yes this is anoying, I can't really test it if it keeps stopping so frequently. Could just resume once the rate limit has cleared.

**Comment by x5a** [comment]
@valdo404 @hippoduck thanks for your feedback. The SDK auto-retries rate limit errors up to 2 times. In the screenshot you pasted, you've got 83 seconds until you can make your next API call, so if we paused your call, we'd be waiting for some time.

**Comment by valdo404** [comment]
well @x5a , I will provide a PR or will clone this project, as I can't accept to have such rate limiting errors in a product context. And I guess closing the issue is not right reflex here.

**Comment by bhs1** [comment]
+1 I also encounter the rate limit issue. Can someone please help?

**Comment by x5a** [comment]
> well @x5a , I will provide a PR or will clone this project, as I can't accept to have such rate limiting errors in a product context. And I guess closing the issue is not right reflex here.

@valdo404 I think you may be misunderstanding the purpose of this repository/demonstration. We intend for you to fork this to build your own applications. This is not a consumer product/general interface for computer use.
