### ISSUE TITLE
The whole screen shot is sent

### ISSUE THREAD

**Issue by valdo404** [anthropics/claude-quickstarts#103]
After each run, it sends the whole screenshot, whichs means the model needs to analyze the whole image again and again.

Which is costly and not very efficient.

Normally just screen updates should be sent, using some image delta or some realtime technology.

Congrats !

**Comment by x5a** [comment]
@valdo404 you can control the number of images sent here:
![CleanShot 2024-10-24 at 10 26 55](https://github.com/user-attachments/assets/c1a8a54c-bd3b-4549-8839-669e51f1fcb5)
