### ISSUE TITLE
It is sending the whole convo each time.

### ISSUE THREAD

**Issue by valdo404** [anthropics/claude-quickstarts#104]
I'm not sure sending the whole convo, with images, screenshots, and everything, each time is efficient. It slows down the computer interaction. Maybe implementing kind of "aggregated" memory would be more efficient than sending everything each time.

**Comment by x5a** [comment]
@valdo404 our API is stateless. You're welcome to extend upon this demonstration by implementing summarization or truncation; implementing is out of scope of this project.

**Comment by valdo404** [comment]
@x5a same here. closing the issue wasn't the expected reply. I'm paying for Anthropic service. Will provide a PR as the current behavior is far from being optimal. The consumed tokens are high, just after some minutes. If you are not open to improvements, just tell it.
