### ISSUE TITLE
[computer-use-demo] Refused to connect in web app

### ISSUE THREAD

**Issue by forcetrainer** [anthropics/claude-quickstarts#108]
Set this up in Ubuntu using the docker image. No errors of any sort that I can see, and I'm able to connect to the NoVNC session on the system.  The web app UI is showing "refused to connect" in both boxes.

The only variable is I am accessing remotely, so it's not via localhost:8080, but [ip]:8080

<img width="500" alt="image" src="https://github.com/user-attachments/assets/0bac6c05-e4e4-4fa8-b0d9-7beeb469346f">

**Comment by forcetrainer** [comment]
Ugh - realized that this is due to not being local, and the index.html file uses localhost or 127.0.0.1 for the links, so it won't work.  Need to run locally or edit the index.html in the container.

**Comment by alvessousaspa** [comment]
Hi, i'm facing the same issue, how you fix it?

**Comment by verchalent** [comment]
You can fix this by creating a mount point for ~/static_content/index.html and then replacing the 127.0.0.1 and localhost entries there with the host IP/DNS
