### ISSUE TITLE
400: This action is restricted for safety reasons at this time.

### ISSUE THREAD

**Issue by benoit-cty** [anthropics/claude-quickstarts#119]
Hello,

The demo is working but 90% of the time I got a 400 error `This action is restricted for safety reasons at this time.`

BTW congratulation for building this so simple test bed !

![image](https://github.com/user-attachments/assets/11d6f207-2e43-4230-ac45-abaf8d1a453a)

**Comment by chrisgorgo** [comment]
Duplicate of #74
