### ISSUE TITLE
computer-use-demo: Spammed by looping tornado.websocket.WebSocketClosedError / tornado.iostream.StreamClosedError

### ISSUE THREAD

**Issue by p-i-** [anthropics/claude-quickstarts#122]
Running computer-use-demo from Docker container, sometimes it seems the UI becomes disconnected.

Inspecting my console (from where I did `docker run`) I see this motif repeated thousands of times:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/tornado/websocket.py", line 1090, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-34447' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/tornado/websocket.py:1086> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/tornado/websocket.py", line 1088, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/tornado/websocket.py", line 1090, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Task exception was never retrieved
future: <Task finished name='Task-34448' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/tornado/websocket.py:1086> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/tornado/websocket.py", line 1088, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:
```

... ad infinitum.

This error should be trapped, and either considered fatal (in which case quit), or some kind of exponential backoff should be applied.

**Comment by x5a** [comment]
@p-i- can you file this against https://github.com/streamlit/streamlit

**Comment by p-i-** [comment]
I did some research into this issue. I think it may be a mistake to toss it over the wall to the streamlit people.

I have a hunch a lot of duplicate data is getting shuttled through the web socket connection, and as the conversation grows in length, a new packet has arrived before the current packet is processed, and it crashes.

If I am roughly correct in this, then they might wish to consider sending only diffs. I myself will not request this of them; I think the request would be significantly stronger, and more likely to get attention, if it were to come from a core Anthropic dev.

Also, it might be worth your while to consider an architectural alternative to streamlit.  I hesitate to make the suggestion, as I do appreciate that this demo is exactly that, a demo, and is a very beautiful and colourful configuration of tech components.

Here are my notes, fwiw.

```
# (Pinned) WebSocket and UI Performance Investigation

## Issue Description
- As conversation length grows, UI becomes increasingly unresponsive
- Eventually leads to WebSocket crashes
- Chrome shows "unresponsive script" warnings
- Finally ends in Tornado WebSocket errors

## Root Cause Analysis
The core issue stems from Streamlit's architecture and how it handles state synchronization:

1. **Streamlit's Rerun Model**
   - Entire script reruns on each interaction
   - Complete state sync over WebSocket each time
   - Growing conversation = growing state = growing sync payload

2. **Expensive Re-rendering**
   - ALL messages re-render each cycle
   - ALL HTTP exchanges re-render each cycle
   - Each tool result lookup and render
   - Full API responses included in state

3. **Compounding Effects**
   - Larger DOM updates as conversation grows
   - Increasing JavaScript state diff/update time
   - WebSocket backlog grows
   - Browser becomes increasingly unresponsive
   - Eventually WebSocket fails under load

## Technical Details
- Error occurs in Tornado's WebSocketProtocol13 (websocket.py:1088)
- StreamClosedError cascades into WebSocketClosedError
- Multiple tasks fail in sequence trying to write messages
- No visible cleanup mechanism for historical data

## Proposed Solutions

### Short Term (Within Streamlit)
1. Implement windowing/pagination
2. Separate HTTP Exchange logs
3. Cache rendered messages
4. Move historical data to separate storage

### Long Term (Architectural)
1. Custom WebSocket state management
   - Version-based state tracking
   - Delta-only updates
   - Client-side state management
   - Render only on actual changes

2. Replace Streamlit with chat-optimized framework
```

**Comment by p-i-** [comment]
For anyone seeking a quick fix to avoid this, I strongly suspect that the act of scrolling forces traffic through the web socket, therefore try to avoid scrolling when the conversation gets long. It might actually be scrolling a long conversation while the AI is still responding and populating the conversation pane. This is very unscientific, but that's my hunch.

**Comment by p-i-** [comment]
I don't think it's related to scrolling, as I just got another crash. Lost another three hours of work.

To try and save my conversation, I used chrome developer tools to select the convo-frame and save the HTML.

```
-rw-r--r--   1 pi  staff   141M 31 Oct 09:04 huge.html
```

141 MB :/

Now I search it for a word that occured only ONCE during the convo, in the first message, and find 172 matches.

A word that occured later gets 86 matches.

There is something seriously wrong here.

**Comment by p-i-** [comment]
I believe I've tracked this down to an O(N^3) json-accumulation issue with HTTP Exchange Logs.
Each interaction-log carries the conversation to date.
So log[5] contains interactions[0, 1, 2, 3, 4]. That's O(N^2).
But if we're sending all prior logs each interaction, so we have a secondary triangle forming on top and the websocket gets burned out as streamlit is transmitting the entire state to the front-end each update.

This might (or might not, haven't tested) work as a stop-gap for anyone wanting to get some work done on this system without crashing.

```diff
diff --git a/computer-use-demo/computer_use_demo/streamlit.py b/computer-use-demo/computer_use_demo/streamlit.py
index 45318ed..539c574 100644
--- a/computer-use-demo/computer_use_demo/streamlit.py
+++ b/computer-use-demo/computer_use_demo/streamlit.py
@@ -2,6 +2,8 @@
 Entrypoint for streamlit, see https://docs.streamlit.io/
 """
 
+DISABLE_HTTP_EXCHANGE_LOGS = True  # Emergency fix for browser memory explosion
+
 import asyncio
 import base64
 import os
@@ -288,6 +290,11 @@ def _api_response_callback(
     """
     Handle an API response by storing it to state and rendering it.
     """
+    if DISABLE_HTTP_EXCHANGE_LOGS:
+        if error:
+            _render_error(error)
+        return
+
     response_id = datetime.now().isoformat()
     response_state[response_id] = (request, response)
     if error:
```

A better solution might be to allow a checkbox next to the "HTTP Exchange Logs" defaulted to OFF. Of course it'll still crash the Python process if someone ON-s it on a long convo.

**Comment by p-i-** [comment]
fwiw StreamLit might consider zipping websocket traffic. I'm not gona ask them; they have 900+ open issues.

**Comment by Quasimondo** [comment]
Thanks for the temporary fix - seems to make things a bit smoother. If the log is really stored and carried along in the session vars instead of local files that can be loaded on demand that sounds really pretty wasteful.

**Comment by p-i-** [comment]
This is what I ended up with:

```diff
diff --git a/computer-use-demo/computer_use_demo/streamlit.py b/computer-use-demo/computer_use_demo/streamlit.py
index 45318ed..894d894 100644
--- a/computer-use-demo/computer_use_demo/streamlit.py
+++ b/computer-use-demo/computer_use_demo/streamlit.py
@@ -82,6 +82,8 @@ def setup_state():
         st.session_state.custom_system_prompt = load_from_storage("system_prompt") or ""
     if "hide_images" not in st.session_state:
         st.session_state.hide_images = False
+    if "enable_http_logs" not in st.session_state:
+        st.session_state.enable_http_logs = False


 def _reset_model():
@@ -143,6 +145,7 @@ async def main():
             ),
         )
         st.checkbox("Hide screenshots", key="hide_images")
+        st.checkbox("Enable HTTP Exchange Logs", key="enable_http_logs")

         if st.button("Reset", type="primary"):
             with st.spinner("Resetting..."):
@@ -285,9 +288,9 @@ def _api_response_callback(
     tab: DeltaGenerator,
     response_state: dict[str, tuple[httpx.Request, httpx.Response | object | None]],
 ):
-    """
-    Handle an API response by storing it to state and rendering it.
-    """
+    if not st.session_state.enable_http_logs:
+        return
+
     response_id = datetime.now().isoformat()
     response_state[response_id] = (request, response)
     if error:
```

<img width="321" alt="Screenshot 2024-11-03 at 11 03 33" src="https://github.com/user-attachments/assets/4475bfe9-a9d2-4855-bbe4-51f42d90781f">


It solves the problem. Tested.

**Comment by Arsh25** [comment]
This issue still exists and is kinda offputting to anyone trying the Computer Use demo. Why hasn't the anthropic team considered the fixed and PR's provider here? 

It's a great demo but breaks even after a few simple steps of trying to browse through a website. I'm surprised some people on here manager to go 3 hours without this, my test workflow broke in like 10 mins
