### ISSUE TITLE
Is there an error when restarting the container? Can't I restart the existing container?

### ISSUE THREAD

**Issue by zhaizibin** [anthropics/claude-quickstarts#124]
![image](https://github.com/user-attachments/assets/bb2621d4-ddda-4fbf-83a0-9d7c79e20766)
Is there an error message when restarting the container determined_fose in Windows? Why can't I start the original container?
Do I need to create a new container every time when I run computer use? This is too troublesome.
Can't I restart the existing container?
Isn't it impossible to save the historical container like this?
Or is there something wrong with me that can be fixed?

2024-10-28 04:13:23 Xvfb is already running on display :1
2024-10-28 04:13:23 starting tint2 on display :1 ...
2024-10-28 04:13:53 tint2 stderr output:
2024-10-28 04:13:53 tint2: Using glib slice allocator (default). Run tint2 with environment variable G_SLICE=always-malloc in case of strange behavior or crashes
2024-10-28 04:13:53 tint2: could not open display!

**Comment by franticOreo** [comment]
Can confirm I am also getting this on MacOS 12.3

**Comment by franticOreo** [comment]
Same issue [here](https://github.com/anthropics/anthropic-quickstarts/issues/78)

**Comment by zhaizibin** [comment]
> Same issue [here](https://github.com/anthropics/anthropic-quickstarts/issues/78)

According to that answer. The current version does not support restarting existing containers.
So, the current version does not support restarting containers, rather than a personal installation and configuration issue.
Are you sure?
So, everyone should have this problem of not being able to restart the container?
Are you sure?

**Comment by zhaizibin** [comment]
So, everyone should have this problem of not being able to restart the container?
Are you sure?

**Comment by zhaizibin** [comment]
So, everyone should have this problem of not being able to restart the container?
Are you sure?

**Comment by nva14** [comment]
Xvfb lock file remains in /tmp after container stopped. Simple solution would be cleaning up of these files right in entrypoint.sh and i can now restart the container.

```
#!/bin/bash
set -e

rm -rf /tmp/.X* /tmp/.x11* 2>/dev/null || true

# the rest of file

```

You can just ask Claude, it can fix this.

**Comment by zhaizibin** [comment]
> entrypoint.sh

![image](https://github.com/user-attachments/assets/58ef996f-deb9-4603-af00-9f1c83484dd5)
The problem was indeed caused by this temporary file, and the cause has been identified.
Just delete this temporary file .X1-lock is sufficient. Thank you.
However,
How to write the command to delete this temporary file in the startup item of the container?
Can you explain it in detail?

**Comment by zhaizibin** [comment]
![16004ba907460bef58fe72d401fc1c2](https://github.com/user-attachments/assets/201c603c-f6c5-4ddf-822f-e84be104f3e2)
1. Required documents for modification
entrypoint.sh
2. The path of this file is
/home/computeruse/entrypoint.sh
3. Modify the content and save it.
As shown in the picture, add
rm -rf /tmp/.X* /tmp/.x11* 2>/dev/null || true
4. Modify file permissions.
docker exec -u root -it admiring_chatterjee /bin/sh
chmod +x /home/computeruse/entrypoint.sh
then,
My container instance can be restarted now. Thank you very much @nva14

**Comment by zhaizibin** [comment]
Has anyone optimized and maintained this line of code? Thank you.

**Comment by dikkietrom** [comment]
claude just fixed itself by taking a screenshot of the last post and applied it to the file, i restarted the container and it runs fine. this is new to me and feels next level, like an instant paradigm shift
