### ISSUE TITLE
Parameter `old_str` is required for command: `str_replace`

### ISSUE THREAD

**Issue by p-i-** [anthropics/claude-quickstarts#127]
```
Tool Use: str_replace_editor
Input: {'command': 'str_replace', 'path': '/host/master_state.md', 'old_str': '', 'new_str': '...blablabla...'}
```

> Parameter `old_str` is required for command: `str_replace`

I encounter this error frequently. The problem is if the AI gets the error, it doesn't subsequently use the tool correctly, it tries a different approach.

```
Tool Use: bash
Input: {'command': "cat > /host/master_state.md << 'EOL'...blablabla...EOL"}
```

And this times out, which is a SECOND problem.

So it has to try a THIRD approach.

Are you failing to make a distinction between `''` and `None` ?

**Comment by x5a** [comment]
https://status.anthropic.com/incidents/yf39k9sw8rqx caused by this now resolved issue
