### ISSUE TITLE
Error: image anthropics/anthropic-quickstarts:computer-use-demo-latest not found.

### ISSUE THREAD

**Issue by nicolezkx1025** [anthropics/claude-quickstarts#128]
export ANTHROPIC_API_KEY=%your_api_key%

An error occurred when I operate this step, 
docker run \
    -e ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY \
    -v /ATRP/.anthropic:/home/computeruse/.anthropic \
    -p 5900:5900 \
    -p 8501:8501 \
    -p 6080:6080 \
    -p 8080:8080 \
    -it ghcr.io/anthropics/anthropic-quickstarts:computer-use-demo-latest

please help me with this error, 
<img width="486" alt="捕获999" src="https://github.com/user-attachments/assets/8747f4ec-c178-4293-a322-a91d4e0f5f0d">

**Comment by gabespound** [comment]
I just cloned and used this.  I got stuck further along in the process, but I can verify I got past this step with the following commands.
```
./setup.sh  # configure venv, install development dependencies, and install pre-commit hooks
docker build . -t computer-use-demo:local
sudo docker run     -e ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY     -v $(pwd)/computer_use_demo:/home/computeruse/computer_use_demo/ `# mount local python module for development`     -v $HOME/.anthropic:/home/computeruse/.anthropic     -p 5900:5900     -p 8501:8501     -p 6080:6080     -p 8080:8080     -it ghcr.io/anthropics/anthropic-quickstarts:computer-use-demo-latest
```

**Comment by x5a** [comment]
Hi @nicolezkx1025, you're facing an issue with either docker or GHCR. I would try [stackoverflow](https://stackoverflow.com/questions/74656167/unable-to-pull-image-from-github-container-registry-ghcr) or the [github community support](https://github.com/orgs/community/discussions). I'm closing this issue as it's unrelated to our repository.
