### ISSUE TITLE
[computer-use] prompt is too long: 213610 tokens > 199999 maximum

### ISSUE THREAD

**Issue by lostmsu** [anthropics/claude-quickstarts#133]
I actually have a custom implementation of the tool. But here's the JSON I submit:

[computer-use.json](https://github.com/user-attachments/files/17551796/computer-use.json)

It is a simple 1024x768 PNG.

I am puzzled as the quickstart (judging from the code) does up to 10 (up to 50 with prompt caching) images. How do they fit? Am I doing something completely wrong?

**Comment by x5a** [comment]
@lostmsu your content block is implicitly being processed as text rather than an image. See [here](https://docs.anthropic.com/en/docs/build-with-claude/tool-use#example-of-tool-result-with-images) for an example of how to properly structure your image tool result.
