### ISSUE TITLE
Security Issue: Agent has access to API keys

### ISSUE THREAD

**Issue by jamesmurdza** [anthropics/claude-quickstarts#143]
This is a security issue regarding the Anthropic Computer Use Demo.

In the README, it says "Avoid giving the model access to sensitive data, such as account login information, to prevent information theft."

However, the same document recommends passing sensitive data such as AWS access keys to the Docker image.

As a result, if the model decides to run a command such as `printenv | grep AWS`, it can access these keys. Attacks are known that would allow a website to induce this behavior, intentionally causing the model to leak the keys.

Essentially, this is a serious security issue that affects anyone building on this demo.

**Comment by x5a** [comment]
@jamesmurdza can you please report here https://hackerone.com/anthropic-vdp

We're considering how to address this - our README explicitly covers this risk both in terms of prompt injection and weak separation between the agent loop and tools.

**Comment by jamesmurdza** [comment]
✅ Submitted the report.

I'd be happy to help you fix this!

Here’s an example here of how it can be done: https://github.com/e2b-dev/secure-computer-use/

The main thing is that there is an API separating the agent and execution environment that does not pass any sensitive information.

Note that you don’t need to use E2B for this to work, but that did make it easier. (The same can also be done with a Docker container and SSH, for example.)
