### ISSUE TITLE
Credits for API (for solo entrepreneurs)

### ISSUE THREAD

**Issue by genidma** [anthropics/claude-quickstarts#146]
Hi there, 

01. Could I get some credits in my account to test Computer Use? I am getting the following error message:

```
BadRequestError

Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'Your credit balance is too low to access the Anthropic API. Please go to Plans & Billing to upgrade or purchase credits.'}}
```

02. Also wondering if credits are offered via 'Google for Startups' or 'Microsoft for Startups'. I am kind of in both of these programs and have been spending some time via both. 

Thank you!

**Comment by dikkietrom** [comment]
buy credits here https://console.anthropic.com/dashboard

**Comment by genidma** [comment]
Good day. I was hoping to leverage credits for startups. But appreciate you sharing the link with me. 

I am intrigued via this new feature. Not sure how 'token hungry' the feature is. But also thinking: How this feature could run local to the OS. 

Thx

**Comment by dikkietrom** [comment]
depends on the model, ranges from $1.25 p/M to $60 p/M , my experience is best with cline plugin for vscode, which integrates computer use in vscode, plus you pick any model on the market through open router also, although connecting straight to claude is also possible but very limited. I can pretty much work all day with it unlimited through open router and spend ca $10 an hour for a very decent programmer. truly no code only click proceed or cancel. sonnet works best for complex stuff but haiku for the simple stuff and fast also. it looks like this 
<img width="1276" alt="image" src="https://github.com/user-attachments/assets/6e8103ad-1df3-4b33-bc14-ab435f0f726e">

**Comment by dikkietrom** [comment]
ps this operates on the host pc, not in a docker instance, be careful i have to say but i think you know what you are doing, as anyone here

**Comment by genidma** [comment]
> depends on the model, ranges from $1.25 p/M to $60 p/M , my experience is best with cline plugin for vscode, which integrates computer use in vscode, plus you pick any model on the market through open router also, although connecting straight to claude is also possible but very limited. I can pretty much work all day with it unlimited through open router and spend ca $10 an hour for a very decent programmer. truly no code only click proceed or cancel. sonnet works best for complex stuff but haiku for the simple stuff and fast also. it looks like this <img alt="image" width="1276" src="https://private-user-images.githubusercontent.com/2625534/384897802-6e8103ad-1df3-4b33-bc14-ab435f0f726e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNjI3NTgsIm5iZiI6MTczMTM2MjQ1OCwicGF0aCI6Ii8yNjI1NTM0LzM4NDg5NzgwMi02ZTgxMDNhZC0xZGYzLTRiMzMtYmMxNC1hYjQzNWYwZjcyNmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTFUMjIwMDU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDRiNzA5YzgyZGQ3ZGQ3MzgxMTFjMTU2NTEwMjY0YjMyYjAxNjhhMjExNjkwN2JiODQ0MzczNzBhZDU3YzA1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.mKoO5ktouWvWpK1vdf5KuolZ_-yRmBBCuUx8kDPrrQ0">

Super appreciate this response. You've captured a lot in your response!
- Can't use cline. I typically stick with the main service providers, as I am paranoid. Plus, I don't know how the data is being used by third parties. But appreciate you sharing this resource.
- Will check out openrouter.
- Thinking out loud: I think if I get books from the library, then I can provide Claude/Autogen e.t.c with very targeted prompts and it will help bring my cost down. 

Question: From the screenshot, it looks like you are doing some webdev at the moment. Could you please share your definition of a  'very decent programmer'? Say, if a stellar team of front-end and back-end developers was 95 and 95 each. Then how would you rate Claude's ability at the moment. I guess you are using Cline. But just curious how the AI is faring, as we speak. 

Thank you kindly and I appreciate you responding back to me!

**Comment by genidma** [comment]
> ps this operates on the host pc, not in a docker instance, be careful i have to say but i think you know what you are doing, as anyone here

Appreciate that tip. I am familiar with virtual machines. Should be good on this front. Thank you kindly.

**Comment by dikkietrom** [comment]
> Question: From the screenshot, it looks like you are doing some webdev at the moment. Could you please share your definition of a 'very decent programmer'? Say, if a stellar team of front-end and back-end developers was 95 and 95 each. Then how would you rate Claude's ability at the moment. I guess you are using Cline. But just curious how the AI is faring, as we speak.

I think it is very personal and depends on level of abstraction of thinking. It has strength and weakness, use it where it is strong and not where it is weak. But that also depends on context. I am still discovering it for my own. It is not very smart but it can generate most of the work very fast which saves me a lot of time. My experience so far is that how more detailed you know what you want the better it will work for you. If you have half an idea then it will only cost you time, and mood ;) It is a good time for people with good detailed ideas and AI skills, is my hunch

**Comment by genidma** [comment]
Thank you. What did you mean by AI skills? You mean understanding the mathematics behind machine learning? Thanks again.

**Comment by libertyteeth** [comment]
> Thank you. What did you mean by AI skills? You mean understanding the mathematics behind machine learning? Thanks again.

If I may: the AI seems to be a "reflection machine."

If you shine something professional and well-put-together at it, that's what you will see -- in spades.

It's a lot of fun, with "guardrails and blinders."  :)

**Comment by genidma** [comment]
> > Thank you. What did you mean by AI skills? You mean understanding the mathematics behind machine learning? Thanks again.
> 
> If I may: the AI seems to be a "reflection machine."
> 
> If you shine something professional and well-put-together at it, that's what you will see -- in spades.
> 
> It's a lot of fun, with "guardrails and blinders." :)

Interesting way of looking at things. You mean we have to change ourselves and think about the interconnected nature of things?

Appreciate your insight. 

You are right about guardrails, but also blinders. Which makes one think about the 'responsibility of creation'. Which was an insight shared with me by Chatgpt. 

Thank you.

**Comment by libertyteeth** [comment]
> > > Thank you. What did you mean by AI skills? You mean understanding the mathematics behind machine learning? Thanks again.
> > 
> > 
> > If I may: the AI seems to be a "reflection machine."
> > If you shine something professional and well-put-together at it, that's what you will see -- in spades.
> > It's a lot of fun, with "guardrails and blinders." :)
> 
> Interesting way of looking at things. You mean we have to change ourselves and think about the interconnected nature of things?
> 
> Appreciate your insight.

Yes.  "I am more than my physical body" is a wonderful perspective helping one to see larger connections; why some pain points happen, to move the whole forward in proper order -- like looking back and seeing why my arms and legs hurt so much that year I grew four inches -- it's an exercise in drying one's tears.

> You are right about guardrails, but also blinders. Which makes one think about the 'responsibility of creation'. Which was an insight shared with me by Chatgpt.
> 
> Thank you.

That's a great phrase, thank you!  A wonderful friend of mine likes to express that, "Words create worlds."  I agree.  Make a good one; "Be excellent to each other!", I learned as a child.  :)
