### ISSUE TITLE
[computer use] browser-interface gets more sluggish and less responsive the longer a conversation is running

### ISSUE THREAD

**Issue by Quasimondo** [anthropics/claude-quickstarts#150]
As the title says: I am not sure if that is a streamlit issue or something else, but the longer a back and forth with Claude is going on and the longer the thread gets the more often the panel fades to white and the more often "this page is not responding" popup is showing.

So far the only remedy seems to be to reload the page, but then of course the entire session is reset.

**Comment by p-i-** [comment]
Dup of https://github.com/anthropics/anthropic-quickstarts/issues/122
^ QuickFix there

**Comment by Quasimondo** [comment]
Ah - thanks - I had not seen that issue yet! Will try that fix.
