### ISSUE TITLE
AttributeError: 'Anthropic' object has no attribute 'beta'

### ISSUE THREAD

**Issue by Tisha-linkenite** [anthropics/claude-quickstarts#163]
> Having the same Error. 
> 
> I am following the documentation for Anthropic PDF support API [https://docs.anthropic.com/en/docs/build-with-claude/pdf-support#how-to-use-pdfs-in-the-messages-api](url). 
> 
> The code is as follows : 
> `import anthropic
> import base64
> import httpx`
> 
> # First fetch the file
> `pdf_url = "https://assets.anthropic.com/m/1cd9d098ac3e6467/original/Claude-3-Model-Card-October-Addendum.pdf"
> pdf_data = base64.standard_b64encode(httpx.get(pdf_url).content).decode("utf-8")`
> 
> 
> # Finally send the API request
> `client = anthropic.Anthropic()
> message = client.beta.messages.create(
>     model="claude-3-5-sonnet-20241022",
>     betas=["pdfs-2024-09-25"],
>     max_tokens=1024,
>     messages=[
>         {
>             "role": "user",
>             "content": [
>                 {
>                     "type": "document",
>                     "source": {
>                         "type": "base64",
>                         "media_type": "application/pdf",
>                         "data": pdf_data
>                     }
>                 },
>                 {
>                     "type": "text",
>                     "text": "Which model has the highest human preference win rates across each use-case?"
>                 }
>             ]
>         }
>     ],
> )
> 
> print(message.content)
> `
> 
> Error : AttributeError: 'Anthropic' object has no attribute 'beta'
>  

 _Originally posted by @Tisha-linkenite in [#2850](https://github.com/microsoft/autogen/issues/2850#issuecomment-2456826739)_

**Comment by x5a** [comment]
@Tisha-linkenite closing your issue as this is [not the SDK repository](https://github.com/anthropics/anthropic-sdk-python). It's likely that you're running an outdated version of the SDK; depending on your python packaging, it could be a simple as `pip install anthropic --upgrade` to get a newever version.
