### ISSUE TITLE
Unable to open Firefox when running  Docker development

### ISSUE THREAD

**Issue by TzahiShimkinn** [anthropics/claude-quickstarts#208]
Hi, 

When building Docker from local I am having an issue where I can't open Firefox. 

I do not see this issue when runnig it from ghcr.io, wondering if anyone had the same issue

**Comment by nxho** [comment]
Hey - how did you fix this?

**Comment by pxz2016** [comment]
@TzahiShimkinn 
Hey - how did you fix this?
