### ISSUE TITLE
Update the Financial Data Analyst README.md File

### ISSUE THREAD

**Issue by darshenpatel** [anthropics/claude-quickstarts#24]
Change 

Clone the repository:
git clone https://github.com/yourusername/financial-ai-assistant.git
cd **financial-ai-assistant**

to 

Clone the repository:
git clone https://github.com/anthropic-quickstarts/financial-data-analyst.git
cd **financial-data-analyst**

**Comment by darshenpatel** [comment]
@alexalbertt - FYI

**Comment by x5a** [comment]
Readme clarified, see https://github.com/anthropics/anthropic-quickstarts/pull/68
