### ISSUE TITLE
[computer use demo] no amd64 image

### ISSUE THREAD

**Issue by 152334H** [anthropics/claude-quickstarts#39]
this is what happens when I execute the quickstart command [here](https://github.com/anthropics/anthropic-quickstarts/tree/main/computer-use-demo#quickstart-running-the-docker-container):

```bash
Unable to find image 'ghcr.io/anthropics/anthropic-quickstarts:computer-use-demo-latest' locally
computer-use-demo-latest: Pulling from anthropics/anthropic-quickstarts
a186900671ab: Pull complete
11b8c3ccc0a8: Pull complete
b8c417d9a08b: Pull complete
41ef30aadf58: Pull complete
d242346c0f08: Pull complete
4f4fb700ef54: Pull complete
1e4db6f38e97: Pull complete
23753c5f0cb8: Pull complete
97d8faa0eaa3: Pull complete
d66b9a1cdf54: Pull complete
fd68c7c2175a: Pull complete
6be24dbe6f34: Pull complete
4c59a376d65a: Pull complete
Digest: sha256:0d93365f910f99b9d44ba573e0353abb446ef0f03521d99535cded0c864916ce
Status: Downloaded newer image for ghcr.io/anthropics/anthropic-quickstarts:computer-use-demo-latest
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested
i'exec ./entrypoint.sh: exec format error
```

**Comment by chrisgorgo** [comment]
We are investigating. In the meantime you can build the container locally with 

```
docker build -t computer-use . && docker run \
    -e ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY \
    -v $HOME/.anthropic:/home/computeruse/.anthropic \
    -p 5900:5900 \
    -p 8501:8501 \
    -p 6080:6080 \
    -p 8080:8080 \
    -it computer-use
 ```

**Comment by 152334H** [comment]
built nicely and executed without error, I think:

![image](https://github.com/user-attachments/assets/9f14bc8f-560b-451b-aa2d-0b8dacf3ee1d)

not sure what is necessary to make VNC connect properly, though.

![image](https://github.com/user-attachments/assets/0f7efe03-6db8-466f-bced-604dba2bf7df)

is there a way to simply use the Bash Tool included in this update without the rest of the desktop usage features? It would be much easier to integrate into existing dev workflows that way IMO

**Comment by chrisgorgo** [comment]
Does this persist after refreshing the browser or restarting the container? Can you access http://localhost:6080/vnc.html or vnc://localhost:5900

**Comment by 152334H** [comment]
restarted browser, removed/reran container.

```
$ cat r.sh
docker run \
  --platform linux/amd64 \
  -e ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY \
  -v $HOME/microservices/anthropic-quickstarts/.anthropic:/home/computeruse/.anthropic \
  -p 5900:5900 \
  -p 8501:8501 \
  -p 6080:6080 \
  -p 8080:8080 \
  -it cud
$ ./r.sh 
Xvfb started successfully on display :1
Xvfb PID: 9
starting tint2 on display :1 ...
starting mutter
starting vnc
PORT=5900
starting noVNC
noVNC started successfully
✨ Computer Use Demo is ready!
➡️  Open http://localhost:8080 in your browser to begin
```

```
495a5c14f0a3   cud                                  "./entrypoint.sh"        7 seconds ago   Up 7 seconds   0.0.0.0:5900->5900/tcp, :::5900->5900/tcp, 0.0.0.0:6080->6080/tcp, :::6080->6080/tcp, 0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 0.0.0.0:8501->8501/tcp, :::8501->8501/tcp   zen_nightingale
```


chrome shows a pending `Connecting...` when i directly access 6080 but is still stuck I believe:
![image](https://github.com/user-attachments/assets/3d460582-2880-4710-8a48-fa9d39c649db)

no change in firefox behavior

**Comment by 152334H** [comment]
note: i have seen other acquaintances get their container running, so I assume this must be a PEBCAK issue on my part somewhere

**Comment by x5a** [comment]
@152334H
* regarding the initial report, when we first made this repo public, there wasn't an AMD64 docker image, wondering if you see the issue with the `ghcr.io/anthropics/anthropic-quickstarts:computer-use-demo-latest` currentlly
* as a workaround for the issues you are experiencing with the combined landing page, you can access streamlit/vnc directly as [documented here](https://github.com/anthropics/anthropic-quickstarts/tree/main/computer-use-demo#accessing-the-demo-app)
