### ISSUE TITLE
"Failed to connect to server" in noVNC

### ISSUE THREAD

**Issue by bmacer** [anthropics/claude-quickstarts#48]
Upon first run, I encountered a `Failed to connect to server` in the noVNC portion of `localhost:8080`.

<img width="1660" alt="image" src="https://github.com/user-attachments/assets/736d5b06-8755-426a-b32c-22f37066b3ff">

The left-side `Claude Computer Use Demo` portion was unaffected.

Issue surfaced in Brave browser, but may not be browser-related.

Ultimately, I discovered a `Crash Annotation GraphicsCriticalError` error in the terminal logs:

```
podman run \      
    -e ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY \
    -v $HOME/.anthropic:/home/computeruse/.anthropic \
    -p 5900:5900 \
    -p 8501:8501 \
    -p 6080:6080 \
    -p 8080:8080 \
    -it ghcr.io/anthropics/anthropic-quickstarts:computer-use-demo-latest
Xvfb started successfully on display :1
Xvfb PID: 4
starting tint2 on display :1 ...
starting mutter
starting vnc
PORT=5900
starting noVNC
noVNC started successfully
✨ Computer Use Demo is ready!
➡️  Open http://localhost:8080 in your browser to begin
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=0.575329) [GFX1-]: glxtest: libpci missing
```

Ultimately, **killing and restarting the container resolved the issue**.

A few caveats:
- I am using Podman instead of Docker (cost reasons).
- Initially I had a non-latest version of Brave that I used.  I have upgraded to the latest version (v1.71.114).

Posting in case feedback is valuable.  As mentioned a container restart resolved my issue.

**Comment by yudataguy** [comment]
see #42

**Comment by bmacer** [comment]
thanks.  maybe the error message will benefit troubleshooting.

**Comment by x5a** [comment]
thanks for the report! our current theory is that the issue is that the x11vnc server is crashing - if anyone encounters this again, the specific log that would be helpful is at `/tmp/x11vnc_stderr.log`; to fetch from a running container:
```
docker exec $(docker ps --filter "ancestor=ghcr.io/anthropics/anthropic-quickstarts:computer-use-demo-latest" --format "{{.ID}}") cat /tmp/x11vnc_stderr.log
```

**Comment by rburhum** [comment]
I added more debugging info about this topic on #42, but it seems it was closed :-(

**Comment by x5a** [comment]
I'm closing this issue as a duplicate of #42, proposed fix here: https://github.com/anthropics/anthropic-quickstarts/issues/42#issuecomment-2433879785
