### ISSUE TITLE
[Computer Use Demo on MacOS] Error: Invalid value: File does not exist: computer_use_demo/streamlit.py

### ISSUE THREAD

**Issue by mbokinala** [anthropics/claude-quickstarts#53]
The following error is produced when running the docker container following the instructions in the [Quickstart ](https://github.com/anthropics/anthropic-quickstarts/tree/main/computer-use-demo)f or the computer use demo:

Note: this is being run on macOS 14.5.

```
Error: Invalid value: File does not exist: computer_use_demo/streamlit.py
```

The full logs output is below:

```
➜  Desktop docker run \
    -e ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY \
    -v $(pwd)/computer_use_demo:/home/computeruse/computer_use_demo/ \
    -v $HOME/.anthropic:/home/computeruse/.anthropic \
    -p 5900:5900 \
    -p 8501:8501 \
    -p 6080:6080 \
    -p 8080:8080 \
    -e WIDTH=1920 \
    -e HEIGHT=1080 \
    -it ghcr.io/anthropics/anthropic-quickstarts:computer-use-demo-latest
Xvfb started successfully on display :1
Xvfb PID: 9
starting tint2 on display :1 ...
starting mutter
starting vnc
PORT=5900
starting noVNC
noVNC started successfully
✨ Computer Use Demo is ready!
➡️  Open http://localhost:8080 in your browser to begin
Usage: streamlit run [OPTIONS] TARGET [ARGS]...
Try 'streamlit run --help' for help.

Error: Invalid value: File does not exist: computer_use_demo/streamlit.py
```

This is what shows up on `locahost:8080`:

<img width="762" alt="image" src="https://github.com/user-attachments/assets/4d3cb3eb-4a9e-440c-8d65-5e00d9106874">

**Comment by x5a** [comment]
👋  @mbokinala you either need to run the docker command directly from the subfolder of the repo or omit the following line from your docker command: 
```
    -v $(pwd)/computer_use_demo:/home/computeruse/computer_use_demo/ \
```
 I'll update the README accordingly.

**Comment by mbokinala** [comment]
Thanks, that fixed it!
