### ISSUE TITLE
Is it possible to have computer use demo save chats between sessions?

### ISSUE THREAD

**Issue by rifeWithKaiju** [anthropics/claude-quickstarts#60]
is there a way to enable the continuation of previous chat and interaction sessions?

**Comment by x5a** [comment]
@rifeWithKaiju thanks for the question. Persistent chats are currently not supported - we tried to launch with a minimal set of features that could give a flavor of the new Claude 3.5 Sonnet capabilities. to help us prioritize, can you share a little bit more about your use case?

**Comment by rifeWithKaiju** [comment]
@x5a thanks for the response.  my use case is simply researching the capabilities of these models.  I just want to explore what could be accomplished with a longer context that builds up over multiple sessions.

**Comment by x5a** [comment]
Hey @rifeWithKaiju - I'm closing this out as won't implement, but if you feel you have a reusable, broadly useful implementation, feel free to share an upstream PR.

My suggestion here is to:
* use the `load_from_storage`/`save_to_storage` in [streamlit.py](https://github.com/anthropics/anthropic-quickstarts/blob/main/computer-use-demo/computer_use_demo/streamlit.py)
* you specifically want to load the file at startup in `setup_state` and save it after the agent loop runs: https://github.com/anthropics/anthropic-quickstarts/blob/main/computer-use-demo/computer_use_demo/streamlit.py#L213 
* you can make the output file controllable via https://docs.streamlit.io/develop/api-reference/widgets/st.text_input
