### ISSUE TITLE
Troubles running the computer use demo

### ISSUE THREAD

**Issue by GuangxingHan** [anthropics/claude-quickstarts#66]
I used the following command to run the docker container, but both http://localhost:8080/ and http://localhost:8501/ did not work.
```
sudo docker run \
    -e ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY \
    -v $HOME/.anthropic:/home/computeruse/.anthropic \
    -p 5900:5900 \
    -p 8501:8501 \
    -p 6080:6080 \
    -p 8080:8080 \
    -it ghcr.io/anthropics/anthropic-quickstarts:computer-use-demo-latest

```
Does anyone have any idea? Thanks

**Comment by bmacer** [comment]
have you tried killing the process altogether and re-running the command a second time?

**Comment by GuangxingHan** [comment]
yes, I tried. But it did not work.

**Comment by gabriben** [comment]
same issue here

**Comment by gabriben** [comment]
stopping and restarting my docker vm worked for me

**Comment by x5a** [comment]
@gabriben @GuangxingHan can you share the output of `docker info`?

**Comment by GuangxingHan** [comment]
@x5a Here is my log for `docker info`. Thanks.

**Comment by x5a** [comment]
@GuangxingHan closing this as a duplicate of #42 - there's a proposed fix here: https://github.com/anthropics/anthropic-quickstarts/issues/42#issuecomment-2433879785 - let me know in that issue if it doesn't work for you

**Comment by GuangxingHan** [comment]
Thanks. I tried the following command with the new docker image. But I have the same error as before
<img width="664" alt="image" src="https://github.com/user-attachments/assets/5f6eee0d-98d2-4e7a-9dc0-8556a9066570">

```
docker run \
    -e ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY \
    -v $HOME/.anthropic:/home/computeruse/.anthropic \
    -p 5900:5900 \
    -p 8501:8501 \
    -p 6080:6080 \
    -p 8080:8080 \
    -it ghcr.io/anthropics/anthropic-quickstarts:computer-use-demo-db8eb41
```

**Comment by GuangxingHan** [comment]
@x5a any idea about this issue? Thank you

**Comment by Yuriks111** [comment]
The container needs 3 ports: 
Main web interface (port 80)
Streamlit app (port 8501)
VNC server (port 6080)

this cmd worked , my-demo is container name: 

docker run -d ^
    --name my-demo ^
    -p 8080:80 ^
    -p 8501:8501 ^
    -p 6080:6080 ^
    computer-use-demo
