### ISSUE TITLE
Gradio app 

### ISSUE THREAD

**Issue by AK391** [anthropics/claude-quickstarts#72]
would be great to have a gradio app in addition to the existing streamlit one

**Comment by x5a** [comment]
hi @AK391 thanks for the feedback.

It's unlikely we'd accept this upstream, but feel free to fork our project and add a gradio frontend.

**Comment by AK391** [comment]
@x5a there is now a repo with gradio implementation: https://github.com/showlab/computer_use_ootb, can gradio app be added here as well as it does not require docker and easier to use for developers on windows imo
