### ISSUE TITLE
Safety error

### ISSUE THREAD

**Issue by dctmfoo** [anthropics/claude-quickstarts#74]
No matter the prompt and in both windows and linux environments, I get this error a min after prompting it. 

➡️  Open http://localhost:8080 in your browser to begin
2024-10-23 08:17:13.523 Uncaught app exception
Traceback (most recent call last):
  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "/home/computeruse/computer_use_demo/streamlit.py", line 357, in <module>
    asyncio.run(main())
  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/computeruse/computer_use_demo/streamlit.py", line 213, in main
    st.session_state.messages = await sampling_loop(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/computeruse/computer_use_demo/loop.py", line 105, in sampling_loop
    raw_response = client.beta.messages.with_raw_response.create(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/anthropic/_legacy_response.py", line 377, in wrapped
    return cast(LegacyAPIResponse[R], func(*args, **kwargs))
                                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/anthropic/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/anthropic/resources/beta/messages/messages.py", line 896, in create
    return self._post(
           ^^^^^^^^^^^
  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/anthropic/_base_client.py", line 1277, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/anthropic/_base_client.py", line 954, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/anthropic/_base_client.py", line 1058, in _request
    raise self._make_status_error_from_response(err.response) from None
anthropic.BadRequestError: Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'This action is temporarily not available at this time due to enhanced protections for the beta release.'}}
    
    Here are some of the actions done by computer-use before it threw the above error
    
    
![image](https://github.com/user-attachments/assets/feb688cd-1e29-4a3b-8a62-64b87c249e41)

**Comment by dctmfoo** [comment]
So far tried deleting the image and pulling again but no luck!

**Comment by dctmfoo** [comment]
Strange that I get the exact error even after building docker image using the below instructions from Readme

./setup.sh  # configure venv, install development dependencies, and install pre-commit hooks
docker build . -t computer-use-demo:local  # manually build the docker image (optional)
export ANTHROPIC_API_KEY=%your_api_key%
docker run \
    -e ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY \
    -v $(pwd)/computer_use_demo:/home/computeruse/computer_use_demo/ `# mount local python module for development` \
    -v $HOME/.anthropic:/home/computeruse/.anthropic \
    -p 5900:5900 \
    -p 8501:8501 \
    -p 6080:6080 \
    -p 8080:8080 \
    -it computer-use-demo:local  # can also use ghcr.io/anthropics/anthropic-quickstarts:computer-use-demo-latest

**Comment by takielias** [comment]
Same here

**Comment by scamurcuoglu** [comment]
Same here as well, using the README development example on Linux. For me it happens after executing a few steps of the task I requested on the web page

**Comment by chrisgorgo** [comment]
The error `This action is temporarily not available at this time due to enhanced protections for the beta release.` is unrelated to the OS or environment. This is one of our safety interventions. Would you mind sharing what prompts and screenshots triggered it?

**Comment by scamurcuoglu** [comment]
For me the prompts that cause it are some variations of 

"Go to gurulia.com, find mark dawson's profile and click on it to go to his profile page"

**Comment by chrisgorgo** [comment]
thanks - I was able to replicate

**Comment by techybolek** [comment]
So what's the resolution? I've got a pretty much non-working orignal demo

**Comment by abhijitherekar** [comment]
I am also running into the same issue, I have a simple app which scrapes the web content and it fails with `This action is restricted for safety reasons at this time`.

Any resolution ? Like what is exactly causing this because, at this point nothing is working. 

@chrisgorgo , please let us know. Any reply would be appreciated.

**Comment by MikeTheAnomaly** [comment]
> I am also running into the same issue, I have a simple app which scrapes the web content and it fails with `This action is restricted for safety reasons at this time`.
> 
> Any resolution ? Like what is exactly causing this because, at this point its not working.
> 
> @chrisgorgo , please let us know. Any reply would be appreciated.

@abhijitherekar 
I have also been running into this issue today, even though the Docker container previously worked.

Safe to say check back when there status returns to green. 11/4
[https://status.anthropic.com/](https://status.anthropic.com/)

**Comment by abhijitherekar** [comment]
I have very basic prompts like: summarize the content of a website: "URL".  

It works if its a direct prompt but it fails if its a in-direct prompt. 

It was working before, but from today I am seeing this issue and the status page is RED from 2 days.

**Comment by vmandrilly1** [comment]
Yep, I can't even ask it the most basic things to test it: getting the news. I guess it's a safety concern...
It still feels weird that Anthropic can develop an intelligent model, yet they cannot use their model to accurately flag if your request is a normal request or if it is unethical...

**Comment by scamurcuoglu** [comment]
As far as I understand, one of the cases that triggers it is if it sees anything technical or code-like on your screen. So minimizing IDEs/terminals helps

**Comment by vmandrilly1** [comment]
Thanks. But since the model is supposed to be able to use bash and code, that would be highly surprising, and again, has nothing to do with ethical / behavior that should be restricted.

**Comment by abhijitherekar** [comment]
This is crazy and mind boggling, why the model is worried about a users ethical and security concern? Doesn't make sense to me. 
Its upto to the user to decide the security concerns. 

The most important thing is the functionality. Whats use of the product if the functionality itself doesn't work. 
I am asking it a very basic question and it fails with the safety concern. 

I could have understood if anthropic is a security company.

**Comment by MikeTheAnomaly** [comment]
I also noticed my application was failing due to the election being in the
news on sites like Google and Bing. (Google.com had an election-related
image for the Google Doodle.) This bug is incredibly annoying to debug
since it's vague. It would be nice if it cited which rules were broken.

**Comment by x5a** [comment]
This should now be resolved
