### ISSUE TITLE
streamlit deploy error: No module named 'computer_use_demo'

### ISSUE THREAD

**Issue by dvlin-dev** [anthropics/claude-quickstarts#75]
![image](https://github.com/user-attachments/assets/cc1d2e52-8360-42a9-86c0-f7d34e5728b5)
![image](https://github.com/user-attachments/assets/b0929dc6-31c2-43b5-a249-183226334054)

**Comment by x5a** [comment]
Hey @dvlin-dev, we currently don't support the streamlit deploy action - the streamlit is there as a barebones UI, but can't be deployed externally.

**Comment by PriyankaHundalekar** [comment]
Hi Team,

i am facing this issue while running the streamlit application
![Image](https://github.com/user-attachments/assets/fb3e6e8c-b7c9-4afd-913f-3fd730a68631)
