### ISSUE TITLE
tint2 with environment variable err

### ISSUE THREAD

**Issue by minit0181** [anthropics/claude-quickstarts#78]
The first startup was successful, great. but...
If start with [docker start] from the second time onwards, an error will occur.

------------------------------------------------------------------
C:\Windows>docker start -i computer_use
Xvfb is already running on display :1
starting tint2 on display :1 ...
tint2 stderr output:
tint2: Using glib slice allocator (default). Run tint2 with environment variable G_SLICE=always-malloc in case of strange behavior or crashes
tint2: could not open display!
-------------------------------------------------------------------

Is it not possible to [docker start]?

**Comment by x5a** [comment]
@oyamadasan this is currently not supported - `docker start` re-executes the entrypoint, which attempts to restart the already started startup sequence. feel free to submit a PR if you have a fix here.
