### ISSUE TITLE
Proposed fix for startup command when using AWS SSO

### ISSUE THREAD

**Issue by dgurns** [anthropics/claude-quickstarts#81]
In the Readme, the current AWS startup command doesn't work if you are using SSO. This is because the Docker container needs more of the `~/.aws` folder exposed in order to access full data about the current SSO session.

The command should read:

```bash
export AWS_PROFILE=<your_aws_profile>
docker run \
    -e API_PROVIDER=bedrock \
    -e AWS_PROFILE=$AWS_PROFILE \
    -e AWS_REGION=us-west-2 \
    -v $HOME/.aws:/home/computeruse/.aws \
    -v $HOME/.anthropic:/home/computeruse/.anthropic \
    -p 5900:5900 \
    -p 8501:8501 \
    -p 6080:6080 \
    -p 8080:8080 \
    -it ghcr.io/anthropics/anthropic-quickstarts:computer-use-demo-latest
```

I'd be happy to PR this but don't have push access to the repo. 

Thanks for a great demo.

**Comment by chrisgorgo** [comment]
Thanks! Would you mind making a fork and sending PR from there? Appreciated!

**Comment by joerawr** [comment]
What error are you seeing with that?

I am seeing 'anthropic.PermissionDeniedError: Error code: 403 - {'message': "You don't have access to the model with the specified model ID."}' even with Bedrock:*

Wondering if that is my issue.

**Comment by x5a** [comment]
@joerawr there's an explicit [model access request process](https://docs.aws.amazon.com/bedrock/latest/userguide/model-access-modify.html) on bedrock, which I believe is what you're running into.

**Comment by joerawr** [comment]
Yes Sir, that was it.  6 of 7 Anthropic models were selected, and the V2 that the reference image uses is V2.  I enabled it, and we're in.  Thanks!
