### ISSUE TITLE
How much credit should I add? 

### ISSUE THREAD

**Issue by kadavilrahul** [anthropics/claude-quickstarts#83]
I added $25 to test. However tere is error while running script. anthropic.BadRequestError: Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'Your credit balance is too low to access the Anthropic API. Please go to Plans & Billing to upgrade or purchase credits.'}}

**Comment by bmacer** [comment]
I played around some and only had $5.  Ultimately cost about $1.50.  $25 should be more than enough.

**Comment by kadavilrahul** [comment]
![Screenshot_2024-10-23-20-18-03-75_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/a8add24d-bd2c-4891-9d25-713e9c03ec42)

Any idea what is the error about? Attached is my screenshot of Anthropic console.

**Comment by chrisgorgo** [comment]
@kadavilrahul please try again - this should be fixed.

**Comment by mrmaheshdattamishra-crypto** [comment]
I am having the same issue now with $50 credit balance
