### ISSUE TITLE
I ALREADY USE PORT 8080 HOW DO I CHANGE YOUR PORT TO 9090 ?

### ISSUE THREAD

**Issue by jamieduk** [anthropics/claude-quickstarts#84]
docker run \
    -e ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY \
    -v $HOME/.anthropic:/home/computeruse/.anthropic \
    -p 5900:5900 \
    -p 8501:8501 \
    -p 6080:6080 \
    -p 9090:9090 \
    -it ghcr.io/anthropics/anthropic-quickstarts:computer-use-demo-latest

d37c4689d89c: Pull complete 
4f4fb700ef54: Pull complete 
5699d2b7eb4c: Pull complete 
f1d312d052f9: Pull complete 
eb08495f9bb9: Pull complete 
fc6baa9c21c9: Pull complete 
18cb9658fe62: Pull complete 
f17c70e24a85: Pull complete 
1a4b24ae6ff4: Pull complete 
Digest: sha256:619a9d1c408301b17aa1f9f62967f2db576c86ea36a47b384476e123833840b6
Status: Downloaded newer image for ghcr.io/anthropics/anthropic-quickstarts:computer-use-demo-latest
Xvfb started successfully on display :1
Xvfb PID: 9
starting tint2 on display :1 ...
starting mutter
starting vnc
PORT=5900
starting noVNC
noVNC started successfully
✨ Computer Use Demo is ready!
➡️  Open http://localhost:8080 in your browser to begin
x11vnc process crashed, restarting...
x11vnc stderr output:
23/10/2024 11:42:42 No client after 60 secs.
23/10/2024 11:42:42 deleted 32 tile_row polling images.
starting vnc
PORT=5900
x11vnc process crashed, restarting...
x11vnc stderr output:
23/10/2024 11:43:44 No client after 60 secs.
23/10/2024 11:43:44 deleted 32 tile_row polling images.
starting vnc
PORT=5900
x11vnc process crashed, restarting...
x11vnc stderr output:
23/10/2024 11:44:46 No client after 60 secs.
23/10/2024 11:44:46 deleted 32 tile_row polling images.
starting vnc
PORT=5900
x11vnc process crashed, restarting...
x11vnc stderr output:
23/10/2024 11:45:48 No client after 60 secs.
23/10/2024 11:45:48 deleted 32 tile_row polling images.
starting vnc
PORT=5900
x11vnc process crashed, restarting...
x11vnc stderr output:
23/10/2024 11:46:50 No client after 60 secs.
23/10/2024 11:46:50 deleted 32 tile_row polling images.
starting vnc
PORT=5900
x11vnc process crashed, restarting...
x11vnc stderr output:
23/10/2024 11:47:52 No client after 60 secs.
23/10/2024 11:47:52 deleted 32 tile_row polling images.
starting vnc
PORT=5900
x11vnc process crashed, restarting...
x11vnc stderr output:
23/10/2024 11:48:54 No client after 60 secs.
23/10/2024 11:48:54 deleted 32 tile_row polling images.
starting vnc
PORT=5900
x11vnc process crashed, restarting...
x11vnc stderr output:
23/10/2024 11:49:57 No client after 60 secs.
23/10/2024 11:49:57 deleted 32 tile_row polling images.
starting vnc
PORT=5900
x11vnc process crashed, restarting...
x11vnc stderr output:
23/10/2024 11:51:04 No client after 60 secs.
23/10/2024 11:51:04 deleted 32 tile_row polling images.
starting vnc
PORT=5900
x11vnc process crashed, restarting...
x11vnc stderr output:
23/10/2024 11:52:11 No client after 60 secs.
23/10/2024 11:52:11 deleted 32 tile_row polling images.
starting vnc
PORT=5900
x11vnc process crashed, restarting...
x11vnc stderr output:
23/10/2024 11:53:18 No client after 60 secs.
23/10/2024 11:53:18 deleted 32 tile_row polling images.
starting vnc
PORT=5900

**Comment by jamieduk** [comment]
this is dockerfile

```
FROM docker.io/ubuntu:22.04

# Set environment to non-interactive for apt-get commands
ENV DEBIAN_FRONTEND=noninteractive
ENV DEBIAN_PRIORITY=high

# Install sudo first
RUN apt-get update && apt-get install -y sudo || true

# Install necessary packages for X11 and Wayland with sudo
RUN sudo apt update --fix-missing && \
    sudo apt-get install -y \
    build-essential \
    xvfb \
    xterm \
    xdotool \
    scrot \
    imagemagick \
    mutter \
    x11vnc \
    wayland-protocols \
    weston \
    libwayland-dev \
    libwayland-client0 \
    libwayland-server0 \
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    curl \
    git \
    libncursesw5-dev \
    xz-utils \
    tk-dev \
    libxml2-dev \
    libxmlsec1-dev \
    libffi-dev \
    liblzma-dev \
    net-tools \
    libreoffice \
    x11-apps \
    xpdf \
    gedit \
    xpaint \
    tint2 \
    galculator \
    pcmanfm \
    unzip || true

# Add Mozilla team repository and update (optional, consider removing if unnecessary)
RUN sudo add-apt-repository ppa:mozillateam/ppa && \
    sudo apt update --fix-missing || true

# Install noVNC
RUN sudo git clone --branch v1.5.0 https://github.com/novnc/noVNC.git /opt/noVNC && \
    sudo git clone --branch v0.12.0 https://github.com/novnc/websockify /opt/noVNC/utils/websockify && \
    sudo ln -s /opt/noVNC/vnc.html /opt/noVNC/index.html || true

# Setup user
ENV USERNAME=computeruse
ENV HOME=/home/$USERNAME
RUN sudo useradd -m -s /bin/bash -d $HOME $USERNAME || true
RUN echo "${USERNAME} ALL=(ALL) NOPASSWD: ALL" | sudo tee -a /etc/sudoers || true
USER computeruse
WORKDIR $HOME

# Setup Python with pyenv
RUN git clone https://github.com/pyenv/pyenv.git ~/.pyenv && \
    cd ~/.pyenv && src/configure && make -C src && cd .. && \
    echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc && \
    echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc && \
    echo 'eval "$(pyenv init -)"' >> ~/.bashrc || true
ENV PYENV_ROOT="$HOME/.pyenv"
ENV PATH="$PYENV_ROOT/bin:$PATH"
ENV PYENV_VERSION_MAJOR=3
ENV PYENV_VERSION_MINOR=11
ENV PYENV_VERSION_PATCH=6
ENV PYENV_VERSION=$PYENV_VERSION_MAJOR.$PYENV_VERSION_MINOR.$PYENV_VERSION_PATCH
RUN eval "$(pyenv init -)" && \
    pyenv install $PYENV_VERSION && \
    pyenv global $PYENV_VERSION && \
    pyenv rehash || true

ENV PATH="$HOME/.pyenv/shims:$HOME/.pyenv/bin:$PATH"

# Upgrade pip and install Python dependencies
RUN python -m pip install --upgrade pip==23.1.2 setuptools==58.0.4 wheel==0.40.0 && \
    python -m pip config set global.disable-pip-version-check true || true

# Install Python requirements
COPY --chown=$USERNAME:$USERNAME computer_use_demo/requirements.txt $HOME/computer_use_demo/requirements.txt
RUN python -m pip install -r $HOME/computer_use_demo/requirements.txt || true

# Setup desktop environment and app files
COPY --chown=$USERNAME:$USERNAME image/ $HOME
COPY --chown=$USERNAME:$USERNAME computer_use_demo/ $HOME/computer_use_demo/

# Set display environment variables for X11 and Wayland
ARG DISPLAY_NUM=1
ARG HEIGHT=768
ARG WIDTH=1024
ENV DISPLAY_NUM=$DISPLAY_NUM
ENV HEIGHT=$HEIGHT
ENV WIDTH=$WIDTH
ENV WAYLAND_DISPLAY=wayland-0

# Modify entrypoint script to use port 9090 instead of 8080
RUN sudo sed -i 's/8080/9090/g' ./entrypoint.sh || true

# Wayland environment setup
ENV XDG_RUNTIME_DIR=/run/user/1000
RUN mkdir -p $XDG_RUNTIME_DIR && chmod 700 $XDG_RUNTIME_DIR || true

# Update and install xvfb and dbus-x11
RUN sudo apt-get update && sudo apt-get install -y xvfb dbus-x11 || true

# Set default display environment
ENV DISPLAY=:99

ENTRYPOINT ["./entrypoint.sh"]

```

```
docker build -t anthropic-custom .



docker run \
    -e ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY \
    -v $HOME/.anthropic:/home/computeruse/.anthropic \
    -p 5900:5900 \
    -p 8501:8501 \
    -p 6080:6080 \
    -p 9090:9090 \
    -it anthropic-custom
    
    
```
this is for use with ubuntu on rpi 5

this supports wayland aswell as a good 9090 port instead of already used most common port 8080 < dont use common ports retards!

**Comment by jamieduk** [comment]
still dont work cus of fucking bs error

jay@jnetreloaded:~/Documents/Scripts/AI/anthropic-quickstarts/computer-use-demo$ docker run     -e ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY     -v $HOME/.anthropic:/home/computeruse/.anthropic     -p 5900:5900     -p 8501:8501     -p 6080:6080     -p 9090:9090     -it anthropic-custom
Starting Xvfb...
Xvfb failed to start within 10 seconds
Xvfb failed to start

entry file 

```
#!/bin/bash
set -e

# Check if Xvfb is already running and kill it
if pgrep -x "Xvfb" > /dev/null; then
    echo "Stopping existing Xvfb instance..."
    pkill -f "Xvfb"
    sleep 2  # Wait a moment for it to terminate
fi

# Start Xvfb on display :99
echo "Starting Xvfb..."
Xvfb :99 -screen 0 1024x768x16 -ac > /tmp/xvfb.log 2>&1 &
sleep 5  # Wait for Xvfb to start

# Check if Xvfb started successfully
if ! pgrep -x "Xvfb" > /dev/null; then
    echo "Xvfb failed to start."
    echo "Xvfb Log Output:"
    cat /tmp/xvfb.log  # Print the log for debugging
    exit 1
fi

# Set the DISPLAY environment variable
export DISPLAY=:99

# Start other services
./start_all.sh
./novnc_startup.sh

# Start the HTTP server
python http_server.py > /tmp/server_logs.txt 2>&1 &

# Start Streamlit
STREAMLIT_SERVER_PORT=8501 python -m streamlit run computer_use_demo/streamlit.py > /tmp/streamlit_stdout.log &

# Display messages
echo "✨ Computer Use Demo is ready!"
echo "➡️  Open http://localhost:9090 in your browser to begin"

# Keep the container running
tail -f /dev/null

```

**Comment by jamieduk** [comment]
Plz fixit i want this on ubuntu arm 64 bit wayland support ok port 9090 not fkin 8080 i use that for other things like most ppl !!

**Comment by jamieduk** [comment]
reply when all this bs is fixed!

**Comment by NeverBeLazyG** [comment]
what type of noob are you, that you cant even change a number in the docker command.

**Comment by NeverBeLazyG** [comment]
fix your trash system. for everyone its working like a charm. and stop beeing so poor to trying to use it on kiddy sistems like raspberry. buy decent hardware you noob.

**Comment by p-i-** [comment]
Hopefully Anthropic will soon evolve their agentware to automatically remove spam-issues from lazy/stupid/disrespectful users. Anything greedy/needy/ALL-CAPS. These users should be blacklisted.
