### ISSUE TITLE
PermissionDeniedError 403 forbidden

### ISSUE THREAD

**Issue by rehack** [anthropics/claude-quickstarts#86]
Is the lack of permission due to API key?

![image](https://github.com/user-attachments/assets/3d6e06b0-30bc-43aa-bc18-8842fd6068e1)

**Comment by x5a** [comment]
@rehack https://docs.anthropic.com/en/api/supported-regions

**Comment by nowhereman1999** [comment]
> Is the lack of permission due to API key?
> 
> ![image](https://private-user-images.githubusercontent.com/9047357/379356165-3d6e06b0-30bc-43aa-bc18-8842fd6068e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NzIwMTAsIm5iZiI6MTcyOTc3MTcxMCwicGF0aCI6Ii85MDQ3MzU3LzM3OTM1NjE2NS0zZDZlMDZiMC0zMGJjLTQzYWEtYmMxOC04ODQyZmQ2MDY4ZTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjRUMTIwODMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzRhMDM3NWJkOTJkMTM2MmU1OTc0ZTBlZGQ4ZjMzYTAyYTk4MTFiYmZhZGY4MmI0OWQ4Y2I0OWE1MzgwMjZmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Ywk-W-0IbVgCVp3UBwSx_anMxxIw2rHWJOFUB60gQgo)

![image](https://github.com/user-attachments/assets/90e3d55b-490e-4245-9030-f35f614d179c)
Hi，have you already solved the problem？I was running the demo in WSL2 and it throws the same error

**Comment by nowhereman1999** [comment]
> > Is the lack of permission due to API key?
> > ![image](https://private-user-images.githubusercontent.com/9047357/379356165-3d6e06b0-30bc-43aa-bc18-8842fd6068e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NzIwMTAsIm5iZiI6MTcyOTc3MTcxMCwicGF0aCI6Ii85MDQ3MzU3LzM3OTM1NjE2NS0zZDZlMDZiMC0zMGJjLTQzYWEtYmMxOC04ODQyZmQ2MDY4ZTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjRUMTIwODMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzRhMDM3NWJkOTJkMTM2MmU1OTc0ZTBlZGQ4ZjMzYTAyYTk4MTFiYmZhZGY4MmI0OWQ4Y2I0OWE1MzgwMjZmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Ywk-W-0IbVgCVp3UBwSx_anMxxIw2rHWJOFUB60gQgo)
> 
> ![image](https://private-user-images.githubusercontent.com/53631206/379760688-90e3d55b-490e-4245-9030-f35f614d179c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NzIyNDYsIm5iZiI6MTcyOTc3MTk0NiwicGF0aCI6Ii81MzYzMTIwNi8zNzk3NjA2ODgtOTBlM2Q1NWItNDkwZS00MjQ1LTkwMzAtZjM1ZjYxNGQxNzljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDEyMTIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNGJjMWYwN2E1ZmRmZGI5MTUyMWZkNDI2Y2E5MWE1ODg0OTM5MjVkMGU4MzgwNTk1ZjAxYjdlMzcwMTk4NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4AH-YrFxyp-g6H30xd9dqt41uihplfp9Fbh6EZ5QByo) Hi，have you already solved the problem？I was running the demo in WSL2 and it throws the same error

I'm glad to tell you that I've solved the problem, it was caused by docker containers not configured with an agent, please add the following two commands when you create the container:
```
 -e HTTP_PROXY="http://IP:7890" \
 -e HTTPS_PROXY="http://IP:7890" \
```
 replace the` IP` with your proxy address（Generally it's the host address

**Comment by FFchopon** [comment]
> caused by docker containers not configured with an agent

Sorry to bother, i met the same error (PermissionDeniedError 403 forbidden) using the original command. In that case, my container has no internet, and it also shows the error PermissionDeniedError 403 forbidden. Following ur suggestion, i add these two commands when i create the container. Right now my container has internet (can access google, youtube...), but the error PermissionDeniedError 403 forbidden still exist. Do u know how i can try to solve it? By the way, i'm in china mainland.

<img width="1910" height="1031" alt="Image" src="https://github.com/user-attachments/assets/f3922271-b235-4a64-bd4a-0abddb38420e" />
